### ISSUE TITLE
Ubuntu 20.10 clean install, fails to encode with basic settings

### ISSUE THREAD

**Issue by w-barath** [natis1/qencoder#28]
Maybe python 3.8 is too new?
```
sid@shiney:~$ sudo apt install vpx-tools aom-tools ffmpeg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ffmpeg is already the newest version (7:4.3.1-4ubuntu1).
The following NEW packages will be installed:
  aom-tools vpx-tools
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 417 kB of archives.
After this operation, 2,153 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://ca.archive.ubuntu.com/ubuntu groovy/universe amd64 aom-tools amd64 1.0.0.errata1-3build1 [174 kB]
Get:2 http://ca.archive.ubuntu.com/ubuntu groovy/universe amd64 vpx-tools amd64 1.8.2-1build1 [243 kB]
Fetched 417 kB in 1s (304 kB/s)    
Selecting previously unselected package aom-tools.
(Reading database ... 280262 files and directories currently installed.)
Preparing to unpack .../aom-tools_1.0.0.errata1-3build1_amd64.deb ...
Unpacking aom-tools (1.0.0.errata1-3build1) ...
Selecting previously unselected package vpx-tools.
Preparing to unpack .../vpx-tools_1.8.2-1build1_amd64.deb ...
Unpacking vpx-tools (1.8.2-1build1) ...
Setting up aom-tools (1.0.0.errata1-3build1) ...
Setting up vpx-tools (1.8.2-1build1) ...
Processing triggers for man-db (2.9.3-2) ...

sid@shiney:~$ sudo pip3 install qencoder
Collecting qencoder
  Downloading qencoder-1.5.6-py3-none-any.whl (48 kB)
     |████████████████████████████████| 48 kB 884 kB/s 
Collecting scipy
  Downloading scipy-1.5.4-cp38-cp38-manylinux1_x86_64.whl (25.8 MB)
     |████████████████████████████████| 25.8 MB 815 kB/s 
Collecting scenedetect[opencv,progress_bar]
  Downloading scenedetect-0.5.4.1-py2.py3-none-any.whl (106 kB)
     |████████████████████████████████| 106 kB 125 kB/s 
  WARNING: scenedetect 0.5.4.1 does not provide the extra 'progress_bar'
Requirement already satisfied: PyQt5 in /usr/lib/python3/dist-packages (from qencoder) (5.15.0)
Collecting opencv-python
  Downloading opencv_python-4.4.0.46-cp38-cp38-manylinux2014_x86_64.whl (49.5 MB)
     |████████████████████████████████| 49.5 MB 128 kB/s 
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from qencoder) (5.7.2)
Collecting numpy
  Downloading numpy-1.19.4-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 719 kB/s 
Requirement already satisfied: Click in /usr/lib/python3/dist-packages (from scenedetect[opencv,progress_bar]->qencoder) (7.1.2)
Collecting tqdm
  Downloading tqdm-4.54.1-py2.py3-none-any.whl (69 kB)
     |████████████████████████████████| 69 kB 848 kB/s 
Installing collected packages: numpy, scipy, tqdm, opencv-python, scenedetect, qencoder
Successfully installed numpy-1.19.4 opencv-python-4.4.0.46 qencoder-1.5.6 scenedetect-0.5.4.1 scipy-1.5.4 tqdm-4.54.1
sid@shiney:~$ qencoder 
Loading program... please wait!
GLib-GIO-Message: 01:00:43.070: Adding GResources overlay '/org/gnome/nautilus/icons/filmholes.png=/usr/share/icons/filmholes.png'
Unable to load existing preset at: /home/sid/.config/qencoder.qec.
Possibly the first time you have run this, corrupted, or an older version
Do not report this
Writing current settings to config
Running in non-queued mode with a single video
Running
{'video_params': '--threads=4 --tile-columns=1 --tile-rows=0 --cpu-used=8 --rt --end-usage=q --cq-level=28 --bit-depth=8  --i420', 'input_file': PosixPath('/var/www/html/VLC-iOS-Media/MOVIE/z_Clips/Trip Clips/2018-Sept-18-Mountains And Rivers and Bears Oh My-x264.mkv'), 'encoder': 'aom', 'workers': 0, 'audio_params': '-c:a copy', 'threshold': 30, 'logging': None, 'passes': 1, 'output_file': PosixPath('/var/www/html/VLC-iOS-Media/MOVIE/z_Clips/Trip Clips/2018-Sept-18-Mountains And Rivers and Bears Oh My-av1.webm'), 'scenes': None, 'resume': False, 'keep': False, 'min_splits': False, 'pix_format': ' -strict -1 -pix_fmt yuv420p', 'ffmpeg_cmd': '', 'min_split_dist': 0, 'use_vmaf': False, 'threads': 4, 'better_split': True, 'cpuused': 8, 'unsafe_split': True, 'rtenc': True, 'temp': PosixPath('/var/www/html/VLC-iOS-Media/MOVIE/z_Clips/Trip Clips/temp_2018-Sept-18-Mountains And Rivers and Bears Oh My-av1.webm'), 'vmaf_steps': 6, 'min_cq': 25, 'max_cq': 50, 'vmaf_target': 95.0, 'vmaf_path': '', 'boost': False, 'br': 0, 'bl': 0, 'ffmpeg_pipe': '  -strict -1 -pix_fmt yuv420p  -f yuv4mpegpipe - |'}
Error in PySceneDetect: unpack requires a buffer of 208 bytes

Not able to split video. Possibly corrupted.
Traceback (most recent call last):
  File "/home/sid/.local/lib/python3.8/site-packages/qencoder/pav1n.py", line 194, in scene_detect
    scene_list = qencoder.aomkf.aom_keyframes(self.d['input_file'], stat_file, self.d['min_split_dist'], self.d['ffmpeg_pipe'], self.d['encoder'], self.d['threads'] * self.d['workers'], self.d['video_params'], self.d['rtenc'], qinterface)
  File "/home/sid/.local/lib/python3.8/site-packages/qencoder/aomkf.py", line 220, in aom_keyframes
    keyframes = find_aom_keyframes(stat_file, min_scene_len)
  File "/home/sid/.local/lib/python3.8/site-packages/qencoder/aomkf.py", line 122, in find_aom_keyframes
    stats = struct.unpack('d' * 26, frame_buf)
struct.error: unpack requires a buffer of 208 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sid/.local/lib/python3.8/site-packages/qencoder/pav1n.py", line 606, in main_thread
    self.video_encoding(qinterface)
  File "/home/sid/.local/lib/python3.8/site-packages/qencoder/pav1n.py", line 584, in video_encoding
    code = self.setup_routine(qinterface)
  File "/home/sid/.local/lib/python3.8/site-packages/qencoder/pav1n.py", line 571, in setup_routine
    framenums = self.scene_detect(self.d.get('input_file'), qinterface)
  File "/home/sid/.local/lib/python3.8/site-packages/qencoder/pav1n.py", line 270, in scene_detect
    raise Exception
Exception
```

**Comment by natis1** [comment]
Hey w-barath. Can you try installing the latest beta and letting me know if it fails as well?  

sudo pip3 install qencoder==2.0rc6

**Comment by w-barath** [comment]
aomencoder is now throwing out the cmdline and qencoder isn't really noticing the failures.

is lsmash now a dependency or is that an optional addon for filtering?

```
sid@shiney:~$ sudo pip3 uninstall qencoder
sid@shiney:~$ rm -f /home/sid/.config/qencoder.qec 
sid@shiney:~$ rm -rf .local/lib/python3.8/site-packages/qencoder
sid@shiney:~$ sudo pip3 install qencoder==2.0rc6
Collecting qencoder==2.0rc6
  Using cached qencoder-2.0rc6-py3-none-any.whl (48 kB)
Requirement already satisfied: psutil in /usr/lib/python3/dist-packages (from qencoder==2.0rc6) (5.7.2)
Requirement already satisfied: parallelencode in /usr/local/lib/python3.8/dist-packages (from qencoder==2.0rc6) (0.1.10)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.8/dist-packages (from qencoder==2.0rc6) (4.4.0.46)
Requirement already satisfied: PyQt5 in /usr/lib/python3/dist-packages (from qencoder==2.0rc6) (5.15.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from parallelencode->qencoder==2.0rc6) (1.5.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from parallelencode->qencoder==2.0rc6) (1.19.4)
Installing collected packages: qencoder
Successfully installed qencoder-2.0rc6

sid@shiney:~$ qencoder
Error loading lsmash. Either vapoursynth is missing or lsmash is not installed.
Loading program... please wait!
GLib-GIO-Message: 11:10:44.956: Adding GResources overlay '/org/gnome/nautilus/icons/filmholes.png=/usr/share/icons/filmholes.png'
Unable to load existing preset at: /home/sid/.config/qencoder.qec.
Possibly the first time you have run this, corrupted, or an older version
Do not report this
Writing current settings to config
Running in non-queued mode with a single video
Running
0

Encoder encountered an error: 1
Error: Unrecognized option --rt
Usage: aomenc <options> -o dst_filename src_filename
Use --help to see the full list of options.

Encoder encountered an error: 1
Error: Unrecognized option --rt
Usage: aomenc <options> -o dst_filename src_filename
Use --help to see the full list of options.
Error in encoding loop list index out of range
At line 158

[snip dozens of above failures]

Error in encoding loop list index out of range
At line 158

Encoder encountered an error: 1
Error: Unrecognized option --rt
Usage: aomenc <options> -o dst_filename src_filename
Use --help to see the full list of options.
Error in encoding loop list index out of range
At line 158
/home/sid/temp_out.webm/concat: Invalid data found when processing input

Concatenation failed, error
At line: 25
Error:
Finished: 47.8s



Encode completed for /var/www/html/VLC-iOS-Media/MOVIE/z_Clips/Trip Clips/2018-Sept-18-Mountains And Rivers and Bears Oh My-x264.mkv -> /home/sid/out.webm
Enabled all buttons, returning program to normal
```


```
sid@shiney:~$ apt show aom-tools
Package: aom-tools
Version: 1.0.0.errata1-3build1
Priority: optional
Section: universe/video
Source: aom
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Multimedia Maintainers <debian-multimedia@lists.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 849 kB
Depends: libaom0 (>= 1.0.0), libc6 (>= 2.29), libgcc-s1 (>= 3.0), libstdc++6 (>= 5.2)
Homepage: https://aomedia.org/
Download-Size: 174 kB
APT-Manual-Installed: yes
APT-Sources: http://ca.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
Description: AV1 Video Codec Library -- Tools
 AOMedia Video 1 (AV1) is an open and royalty free video encoding format
 optimized for the Internet and the successor of VP9. aom is the
 reference encoder and decoder implementation published by the Alliance
 for Open Media.
 .
 This package contains the command line encoding and decoding tools.
```

I'll look for a aomenc 2.x as it would appear you've using options for that version.

I feel your frustration with aomenc... it doesn't have a --version command and it doesn't have any kind of options export for you to parse other than the --help output which I doubt has stable formatting to be worth parsing.  It has optional codecs... I'm assuming svt_av1 is one of them but there's no way to identify which are available.  Not ideal.

**Comment by w-barath** [comment]
Success.  qencoder 2 + aomenc 2 = shockingly faster than any previous AV1 encoding I've ever tried.  Now I just gotta fiddle around to find the right dials to get the speed/quality tradeoffs I'm shooting for and I can kiss x265 goodbye.  Whew.  Thanks! 👍🏼

**Comment by natis1** [comment]
Yeah. it looks like your aomenc version needs to be higher. I am going back and forth on how to support VERY old aomenc versions but I think I won't make any effort to support 1.0.0-errata because it's INCREDIBLY SLOW. Like. probably 1/5th or less the performance of the newest aomenc version. Glad you figured it out! Let me know if you have any other problems or I will close the issue

**Comment by natis1** [comment]
With that said I definitely need to update the readme for Ubuntu to provide instructions on how to build a modern version of aomenc

**Comment by w-barath** [comment]
For anyone else who ends up here...

$ sudo apt install cmake yasm
$ mkdir ~/github
$ cd ~/github
$ git clone https://aomedia.googlesource.com/aom
$ cd aom
$ rm -rf CMakeCache.txt CMakeFiles
$ mkdir -p ../aom_build
$ cd ../aom_build
$ cmake ../aom -DENABLE_CCACHE=1
$ make -j 4
$ sudo mv aomenc /usr/bin

Then restart qencoder and experience the magic!  :-)
